# Generated by Django 4.1.4 on 2023-08-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='session_key',
        ),
    ]
